/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgraficaproyecto;

import GuardarFinanzas.Egresos;
import GuardarFinanzas.EgresosJpaController;
import GuardarFinanzas.Ingresos;
import GuardarFinanzas.IngresosJpaController;
import Proyecto.ConcreteBuilderEgresos;
import Proyecto.ConcreteBuilderIngreso;
import Proyecto.Egreso;
import Proyecto.Ingreso;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import static java.text.DateFormat.Field.DAY_OF_MONTH;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
/*import java.sql.Date;*/
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import static java.util.logging.Logger.getLogger;
import static javafx.scene.input.KeyCode.AT;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import static javax.print.attribute.Size2DSyntax.MM;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alvarado Legrand
 */
public class InterfazProyecto extends javax.swing.JFrame {

    EntityManagerFactory emf = Persistence.createEntityManagerFactory("ProyectoAD2PU");
    IngresosJpaController AT = new IngresosJpaController(emf);
    EgresosJpaController EG = new EgresosJpaController(emf);
    static Date dNow = new Date( );
    static SimpleDateFormat ft = new SimpleDateFormat ("yyyy-MM-dd");
    
    /**
     * Creates new form InterfazProyecto
     */
    public InterfazProyecto() {
        initComponents();
        this.setResizable(false);
        this.setSize(1015, 550);
        Meses.addItem("");
        Meses.addItem("Enero");
        Meses.addItem("Febrero");
        Meses.addItem("Marzo");
        Meses.addItem("Abril");
        Meses.addItem("Mayo");
        Meses.addItem("Junio");
        Meses.addItem("Julio");
        Meses.addItem("Agosto");
        Meses.addItem("Septiembre");
        Meses.addItem("Octubre");
        Meses.addItem("Noviembre");
        Meses.addItem("Diciembre");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ingresar = new javax.swing.JPanel();
        IngresosLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EgresosLabel = new javax.swing.JLabel();
        ingresosPanel = new javax.swing.JPanel();
        VentasDeProductosLabbel = new javax.swing.JLabel();
        VentasDeProductosTx = new javax.swing.JTextField();
        VentasDeServiciosLabel = new javax.swing.JLabel();
        VentasDeServiciosTx = new javax.swing.JTextField();
        ingresarFinanzaBoton = new javax.swing.JButton();
        PanelEgresos = new javax.swing.JPanel();
        CostoDeMercanciaLabel = new javax.swing.JLabel();
        AlquileresLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CostoDeMercanciaTX = new javax.swing.JTextField();
        AlquileresTx = new javax.swing.JTextField();
        ArticulosDeOficinaTx = new javax.swing.JTextField();
        ServiciosPublicosTx = new javax.swing.JTextField();
        ImpuestosTx = new javax.swing.JTextField();
        SueltosTx = new javax.swing.JTextField();
        ingresarEgresos = new javax.swing.JButton();
        ingresosBoton = new javax.swing.JRadioButton();
        egresosBoton = new javax.swing.JRadioButton();
        Regresar = new javax.swing.JButton();
        VerFinanzas = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RegresarBoton = new javax.swing.JButton();
        Meses = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaModeloIngresos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaModeloEgresos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        Ingresar.setMinimumSize(new java.awt.Dimension(750, 550));
        Ingresar.setPreferredSize(new java.awt.Dimension(750, 550));
        Ingresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IngresosLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        IngresosLabel.setText("Ingresos");
        Ingresar.add(IngresosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("INGRESAR FINANZAS");
        Ingresar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        EgresosLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        EgresosLabel.setText("Egresos");
        Ingresar.add(EgresosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        ingresosPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VentasDeProductosLabbel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        VentasDeProductosLabbel.setText("Ventas De Productos   Q");
        ingresosPanel.add(VentasDeProductosLabbel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 21, -1, -1));

        VentasDeProductosTx.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ingresosPanel.add(VentasDeProductosTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 17, 74, -1));

        VentasDeServiciosLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        VentasDeServiciosLabel.setText("Ventas De Servicios    Q");
        ingresosPanel.add(VentasDeServiciosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 73, -1, -1));

        VentasDeServiciosTx.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ingresosPanel.add(VentasDeServiciosTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 69, 74, -1));

        ingresarFinanzaBoton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ingresarFinanzaBoton.setText("Ingresar");
        ingresarFinanzaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarFinanzaBotonActionPerformed(evt);
            }
        });
        ingresosPanel.add(ingresarFinanzaBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 140, 112, -1));

        Ingresar.add(ingresosPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 300, 200));

        PanelEgresos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CostoDeMercanciaLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CostoDeMercanciaLabel.setText("Costo De Mercancia   Q");
        PanelEgresos.add(CostoDeMercanciaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 17, -1, -1));

        AlquileresLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AlquileresLabel.setText("Alquileres                    Q");
        PanelEgresos.add(AlquileresLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Articulos De Oficina    Q");
        PanelEgresos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 89, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Servicios Publicos      Q");
        PanelEgresos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 125, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Impuestos                    Q");
        PanelEgresos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 161, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Sueldos                        Q");
        PanelEgresos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 203, -1, -1));
        PanelEgresos.add(CostoDeMercanciaTX, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 15, 86, -1));
        PanelEgresos.add(AlquileresTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 48, 86, -1));
        PanelEgresos.add(ArticulosDeOficinaTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 87, 86, -1));
        PanelEgresos.add(ServiciosPublicosTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 123, 86, -1));
        PanelEgresos.add(ImpuestosTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 159, 86, -1));
        PanelEgresos.add(SueltosTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 198, 86, -1));

        ingresarEgresos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ingresarEgresos.setText("Ingresar");
        ingresarEgresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarEgresosActionPerformed(evt);
            }
        });
        PanelEgresos.add(ingresarEgresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        Ingresar.add(PanelEgresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 420, 310));

        ingresosBoton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ingresosBoton.setText("Ingresos");
        ingresosBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresosBotonMouseClicked(evt);
            }
        });
        ingresosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresosBotonActionPerformed(evt);
            }
        });
        Ingresar.add(ingresosBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        egresosBoton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        egresosBoton.setText("Egresos");
        egresosBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                egresosBotonMouseClicked(evt);
            }
        });
        egresosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                egresosBotonActionPerformed(evt);
            }
        });
        Ingresar.add(egresosBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, -1));

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        Ingresar.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, -1, -1));

        VerFinanzas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VerFinanzas.png"))); // NOI18N
        jLabel1.setText("Historial Finanzas");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        RegresarBoton.setText("Regresar");
        RegresarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarBotonActionPerformed(evt);
            }
        });
        jPanel3.add(RegresarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, -1, -1));

        Meses.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MesesItemStateChanged(evt);
            }
        });
        jPanel3.add(Meses, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 150, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Historial Mes");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        TablaModeloIngresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Fecha", "Ingresos"
            }
        ));
        TablaModeloIngresos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(TablaModeloIngresos);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 350, -1));

        TablaModeloEgresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Fecha", "Egresos"
            }
        ));
        jScrollPane2.setViewportView(TablaModeloEgresos);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 350, -1));

        VerFinanzas.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 550));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ingresar Finanzas");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Finanzas.png"))); // NOI18N
        jLabel8.setText("Finanzas");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ver Finanzas");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 550));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoPrincipal (1).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 660, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarFinanzaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarFinanzaBotonActionPerformed
        // TODO add your handling code here:
        egresosBoton.setEnabled(true);
        ingresosPanel.setVisible(false);
        PanelEgresos.setVisible(false);
        egresosBoton.setSelected(false);
        ingresosBoton.setSelected(false);
        if((VentasDeProductosTx.getText().equals(""))||(VentasDeServiciosTx.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "Debe de llenar todos los campos antes de ingresar Q 0");
        }else{
            float VDP = Float.parseFloat(VentasDeProductosTx.getText()),VDS= Float.parseFloat(VentasDeServiciosTx.getText());
            Ingreso fecha = new Ingreso(ft.format(dNow).toString());
            ConcreteBuilderIngreso CBIN = new ConcreteBuilderIngreso(fecha);
            CBIN.AgregarIngresos(VDP,VDS);
            Ingresos ingreso = new Ingresos();
            ingreso.setId(0l);
            ingreso.setVentasDeProductos(fecha.getVentasDeProductos());
            ingreso.setVentasDeServicios(fecha.getVentasDeServicios());
            ingreso.setFecha(ingreso.getFecha());
            ingreso.setGananciaTotal(fecha.getGananciaBruta());
            AT.create(ingreso);
            JOptionPane.showMessageDialog(null, "Ingresos guardados en la fecha: "+ft.format(dNow).toString());
            System.out.println("Fecha Guardado: "+ingreso.getFecha());
            VentasDeProductosTx.setText("");
            VentasDeServiciosTx.setText("");
        }
    }//GEN-LAST:event_ingresarFinanzaBotonActionPerformed

    private void ingresarEgresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarEgresosActionPerformed
        // TODO add your handling code here:
        ingresosBoton.setEnabled(true);
        PanelEgresos.setVisible(false);
        ingresosPanel.setVisible(false);
        egresosBoton.setSelected(false);
        ingresosBoton.setSelected(false);
        Egreso fecha = new Egreso(ft.format(dNow).toString());
        Egresos egresos = new Egresos();
        ConcreteBuilderEgresos CBEG = new ConcreteBuilderEgresos(fecha);
        if((CostoDeMercanciaTX.getText().equals(""))||(ArticulosDeOficinaTx.getText().equals(""))||(ImpuestosTx.getText().equals(""))||(AlquileresTx.getText().equals(""))||(ServiciosPublicosTx.getText().equals(""))||(SueltosTx.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "Debe de llenar todos los campos antes de ingresar o colocar Q 0");
        }else{
            float CDM = Float.parseFloat(CostoDeMercanciaTX.getText()),ART = Float.parseFloat(ArticulosDeOficinaTx.getText()),IM = Float.parseFloat(ImpuestosTx.getText()),
            AL =  Float.parseFloat(AlquileresTx.getText()), sv = Float.parseFloat(ServiciosPublicosTx.getText()),SUEL = Float.parseFloat(SueltosTx.getText());
            CBEG.AgregarEgresos(CDM, AL, ART, sv, IM, SUEL);
            egresos.setId(0l);
            egresos.setCostoDeMercancia(fecha.getCostoDeMercancia());
            egresos.setArticulosDeOficina(fecha.getArticulosDeOficina());
            egresos.setImpuestos(fecha.getImpuestos());
            egresos.setAlquiler(fecha.getAlquiler());
            egresos.setSueldos(fecha.getSueldos());
            egresos.setServiciosPublicos(fecha.getServiciosPublicos());
            egresos.setPerdidaTotal(fecha.getPerdidaTotal());
            egresos.setFecha(egresos.getFecha());
            EG.create(egresos);
            JOptionPane.showMessageDialog(null, "Egresos guardados en la fecha: "+ft.format(dNow).toString());
            CostoDeMercanciaTX.setText("");
            ArticulosDeOficinaTx.setText("");
            ImpuestosTx.setText("");
            AlquileresTx.setText("");
            ServiciosPublicosTx.setText("");
            SueltosTx.setText("");
        }
        
    }//GEN-LAST:event_ingresarEgresosActionPerformed

    private void ingresosBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresosBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresosBotonMouseClicked

    private void ingresosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresosBotonActionPerformed
        ingresosPanel.setVisible(true);
        PanelEgresos.setVisible(false);
        egresosBoton.setEnabled(false);
        egresosBoton.setSelected(false);
        ingresosBoton.setSelected(true);
    }//GEN-LAST:event_ingresosBotonActionPerformed

    private void egresosBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_egresosBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_egresosBotonMouseClicked

    private void egresosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_egresosBotonActionPerformed
        ingresosPanel.setVisible(false);
        PanelEgresos.setVisible(true);
        ingresosBoton.setEnabled(false);
        egresosBoton.setSelected(true);
        ingresosBoton.setSelected(false);
    }//GEN-LAST:event_egresosBotonActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        Ingresar.setVisible(false);
        ingresosBoton.setSelected(false);
        ingresosBoton.setEnabled(true);
        egresosBoton.setSelected(false);
        egresosBoton.setEnabled(true);
        CostoDeMercanciaTX.setText("");
        ArticulosDeOficinaTx.setText("");
        ImpuestosTx.setText("");
        AlquileresTx.setText("");
        ServiciosPublicosTx.setText("");
        SueltosTx.setText("");
        VentasDeProductosTx.setText("");
        VentasDeServiciosTx.setText("");
        this.getContentPane().remove(Ingresar);
    }//GEN-LAST:event_RegresarActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        DefaultTableModel tabla = (DefaultTableModel) TablaModeloIngresos.getModel();
        DefaultTableModel tabla2 = (DefaultTableModel) TablaModeloEgresos.getModel();
        tabla.setRowCount(0);
        tabla2.setRowCount(0);
        Meses.setSelectedIndex(0);
        this.getContentPane().add(Ingresar);
        Ingresar.setLocation(250, 0);
        Ingresar.setSize(750, 550);
        Ingresar.setVisible(true);
        this.setSize(1016, 550);
        PanelEgresos.setVisible(false);
        ingresosPanel.setVisible(false);
        VerFinanzas.setVisible(false);
      
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
//        ModeloTabla TablaPrincipal = new ModeloTabla(new IngresosJpaController(emf), new EgresosJpaController(emf));
//        TablaModelo.setModel(TablaPrincipal);
        this.getContentPane().add(VerFinanzas);
        VerFinanzas.setLocation(250, 0);
        VerFinanzas.setSize(750, 550);
        VerFinanzas.setVisible(true);
        this.setSize(1016, 550);
        Ingresar.setVisible(false);
       
    }//GEN-LAST:event_jLabel10MouseClicked

    private void RegresarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarBotonActionPerformed
            VerFinanzas.setVisible(false);
            DefaultTableModel tabla = (DefaultTableModel) TablaModeloIngresos.getModel();
            DefaultTableModel tabla2 = (DefaultTableModel) TablaModeloEgresos.getModel();
            tabla.setRowCount(0);
            Meses.setSelectedIndex(0);
            this.getContentPane().remove(VerFinanzas);        
    }//GEN-LAST:event_RegresarBotonActionPerformed

    private void MesesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MesesItemStateChanged
        try {
            DefaultTableModel tabla = (DefaultTableModel) TablaModeloIngresos.getModel();
            DefaultTableModel tablaeg = (DefaultTableModel) TablaModeloEgresos.getModel();
            tabla.setRowCount(0);
            tablaeg.setRowCount(0);
            String inicio = "2018-"+Meses.getSelectedIndex()+"-01",fin="2018-"+Meses.getSelectedIndex()+"-"+maximoDiasMes(2018,Meses.getSelectedIndex()-1);
            System.out.println("inicio: "+inicio);
            System.out.println("Fin: "+fin);
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            Date fecha = format.parse(inicio);
            Date fecha2 = format.parse(fin);
            java.sql.Date fInicio = new java.sql.Date(fecha.getTime());
            java.sql.Date fFin = new java.sql.Date(fecha2.getTime());
            List<Ingresos> lista= AT.findGananciaPorMes(fInicio,fFin);
            List<Egresos> lista2= EG.fingPerdidaPorMes(fInicio,fFin);
            System.out.println("encontrados = "+lista.size());
            System.out.println("encontrados eg= "+lista2.size());
            for (Ingresos ingreso : lista) {
                tabla.addRow(new String[]{
                    ingreso.getFecha().toString(),
                    Float.toString(ingreso.getGananciaTotal()),
                });
            }
            for (Egresos egresos : lista2) {
                tablaeg.addRow(new String[]{
                    egresos.getFecha().toString(),
                    Float.toString(egresos.getPerdidaTotal()),
                });
            }
            //tabla.addRow(datos);
            TablaModeloIngresos.setModel(tabla);
       
        } catch (ParseException ex) {
            
        }
    }//GEN-LAST:event_MesesItemStateChanged
    public int maximoDiasMes(int anio,int mes){
    Calendar calendario = Calendar.getInstance();
    calendario.set(anio,mes,1);
    return calendario.getActualMaximum(Calendar.DAY_OF_MONTH);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazProyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlquileresLabel;
    private javax.swing.JTextField AlquileresTx;
    private javax.swing.JTextField ArticulosDeOficinaTx;
    private javax.swing.JLabel CostoDeMercanciaLabel;
    private javax.swing.JTextField CostoDeMercanciaTX;
    private javax.swing.JLabel EgresosLabel;
    private javax.swing.JTextField ImpuestosTx;
    private javax.swing.JPanel Ingresar;
    private javax.swing.JLabel IngresosLabel;
    private javax.swing.JComboBox<String> Meses;
    private javax.swing.JPanel PanelEgresos;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton RegresarBoton;
    private javax.swing.JTextField ServiciosPublicosTx;
    private javax.swing.JTextField SueltosTx;
    private javax.swing.JTable TablaModeloEgresos;
    private javax.swing.JTable TablaModeloIngresos;
    private javax.swing.JLabel VentasDeProductosLabbel;
    private javax.swing.JTextField VentasDeProductosTx;
    private javax.swing.JLabel VentasDeServiciosLabel;
    private javax.swing.JTextField VentasDeServiciosTx;
    private javax.swing.JPanel VerFinanzas;
    private javax.swing.JRadioButton egresosBoton;
    private javax.swing.JButton ingresarEgresos;
    private javax.swing.JButton ingresarFinanzaBoton;
    public static javax.swing.JRadioButton ingresosBoton;
    private javax.swing.JPanel ingresosPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
